spring:
  application:
    name: task-management-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: orm-connection-pool
    username: ${DB_USER:user_task_management_api}
    password: ${DB_PASSWORD:12345678}
    url: jdbc:postgresql://${DB_HOST:task-management-db}:${DB_PORT:5432}/task_management_api
  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      lifecycle-management: start_only
      file: compose.yaml

