spring:
  application:
    name: task-management-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: orm-connection-pool
    username: ${DB_USER:user_task_api}
    password: ${DB_PASSWORD:12345678}
    url: jdbc:postgresql://${DB_HOST:task-database}:${DB_PORT:5432}/task_api_database
  threads:
    virtual:
      enabled: true
