name: build-and-test

on:
  push:
    branches: ['feature/**', 'bugfix/**']
  pull_request:
    branches: ['feature/**', 'bugfix/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - run: mvn -B verify --no-transfer-progress
