
name: ci

on:
  push:
    branches: [master]
    tags:    ['v*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: mvn verify
        run: mvn -B verify --no-transfer-progress

  push-image:
    needs: test
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # needed for ghcr.io

    steps:
      - uses: actions/checkout@v4

      # pega versão do pom.xml
      - uses: actions/setup-java@v4
        with: {distribution: temurin, java-version: '24'}
      - id: ver
        run: |
          v=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' \
                 --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          echo "tag=$v" >>"$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.ver.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest

